dataset: capitals_qwen3
output_path: results/case_studies/capitals_qwen3_circuit.pkl
percentage_threshold: 0.005
batch_size: 1
k: 5
apply_blacklist: false
verbose: false
model_id: Qwen/Qwen3-32B
keep_bos: true
gpus_per_model: 2
