# Multilingual antonyms circuit preparation
dataset: multilingual
output_path: results/case_studies/multilingual_circuit.pkl
percentage_threshold: 0.005
batch_size: 1
k: 5
apply_blacklist: true
verbose: false
