# Sensitivity analysis circuit preparation
dataset: sensitivity_analysis
output_path: results/case_studies/sensitivity_analysis_circuit.pkl
percentage_threshold: 0.005
batch_size: 4
k: 5
apply_blacklist: true
verbose: false
