"""
fetch_neuronpedia_prompts.py — pull canonical prompts from Neuronpedia graphs.

Step 0 of the Neuronpedia pipeline. Reads the graph list in
``custom_automation/prompts/neuronpedia_graphs.csv`` (columns: slug, share_url,
notes) and, for each slug, fetches the graph's canonical prompt from the
Neuronpedia graph API:

    https://www.neuronpedia.org/api/graph/<model-id>/<slug>

The API returns the exact prompt (and promptTokens) Neuronpedia traced, which is
more reliable than parsing the "prompt -> answer" note. The leading ``<bos>`` is
stripped (the tokenizer re-adds it) and trailing spaces are preserved so the trace
reproduces Neuronpedia's target token.

Writes two files:
  - scripts/circuit_prep/data/neuronpedia.py    — the prep.py / batch_export_neurons.py
        dataset module (prompts, seed_responses, labels). labels are the slugs.
  - custom_automation/prompts/neuronpedia_prompts.json — slug -> {prompt, answer,
        share_url, prompt_tokens} for reference / the README.

Usage:
    python custom_automation/fetch_neuronpedia_prompts.py
    python custom_automation/fetch_neuronpedia_prompts.py --model-id google/gemma-2-2b
"""

from __future__ import annotations

import argparse
import csv
import json
import logging
import sys
import time
import urllib.error
import urllib.request
from pathlib import Path

logging.basicConfig(level=logging.INFO, format="%(asctime)s %(levelname)s: %(message)s")
log = logging.getLogger(__name__)

REPO_ROOT = Path(__file__).resolve().parent.parent
CSV_FILE = REPO_ROOT / "custom_automation" / "prompts" / "neuronpedia_graphs.csv"
DATASET_FILE = REPO_ROOT / "scripts" / "circuit_prep" / "data" / "neuronpedia.py"
REFERENCE_JSON = REPO_ROOT / "custom_automation" / "prompts" / "neuronpedia_prompts.json"

# The Neuronpedia graph API expects the short model id (e.g. "gemma-2-2b"), while
# tracing uses the HF id ("google/gemma-2-2b"). We accept either and normalize.
API_BASE = "https://www.neuronpedia.org/api/graph"
BOS = "<bos>"


def _api_model_id(model_id: str) -> str:
    """Neuronpedia uses the bare model id (drop any HF org prefix)."""
    return model_id.split("/")[-1]


def fetch_graph(model_id: str, slug: str, retries: int = 3, timeout: int = 30) -> dict:
    """GET the Neuronpedia graph JSON for one slug (with simple backoff retries)."""
    url = f"{API_BASE}/{_api_model_id(model_id)}/{slug}"
    last_exc: Exception | None = None
    for attempt in range(1, retries + 1):
        try:
            req = urllib.request.Request(url, headers={"User-Agent": "adag-fetch/1.0"})
            with urllib.request.urlopen(req, timeout=timeout) as resp:
                return json.loads(resp.read().decode("utf-8"))
        except (urllib.error.URLError, TimeoutError, json.JSONDecodeError) as exc:
            last_exc = exc
            log.warning("  %s attempt %d/%d failed: %s", slug, attempt, retries, exc)
            if attempt < retries:
                time.sleep(2 ** (attempt - 1))
    raise RuntimeError(f"Failed to fetch {url}: {last_exc}")


def extract_prompt(graph: dict) -> tuple[str, list[str]]:
    """Pull (prompt, prompt_tokens) from a graph JSON, with <bos> stripped."""
    prompt = graph.get("prompt")
    tokens = graph.get("promptTokens")
    if prompt is None or tokens is None:
        meta = graph.get("metadata", {})
        prompt = prompt if prompt is not None else meta.get("prompt")
        tokens = tokens if tokens is not None else meta.get("prompt_tokens")
    if prompt is None:
        raise KeyError("graph JSON has no 'prompt' field")
    if prompt.startswith(BOS):
        prompt = prompt[len(BOS):]
    tokens = [t for t in (tokens or []) if t != BOS]
    return prompt, tokens


def answer_from_notes(notes: str) -> str:
    """Parse the answer (text after the arrow) from a CSV note, for documentation."""
    notes = (notes or "").strip()
    for sep in ("→", "->"):  # unicode arrow or ascii
        if sep in notes:
            return notes.split(sep, 1)[1].strip()
    return ""


def _py_literal(s: str) -> str:
    """Render a string as a Python double-quoted literal (json.dumps is a safe superset)."""
    return json.dumps(s, ensure_ascii=False)


def write_dataset_module(rows: list[dict], path: Path) -> None:
    """Write the prep.py / batch_export_neurons.py dataset module."""
    lines = [
        "# -*- coding: utf-8 -*-",
        '"""Neuronpedia gemma-2-2b graph prompts (base-model completion style).',
        "",
        "Generated by custom_automation/fetch_neuronpedia_prompts.py from",
        "custom_automation/prompts/neuronpedia_graphs.csv. Do not edit by hand —",
        "regenerate with:  python custom_automation/fetch_neuronpedia_prompts.py",
        "",
        "Each prompt has the leading <bos> stripped (the tokenizer re-adds it) and",
        "trailing spaces preserved. gemma-2-2b is a base model, so seed_responses are",
        "empty and the trace targets the model's own next-token prediction. labels are",
        "the Neuronpedia slugs. The answer field is documentation only.",
        '"""',
        "",
        "# (slug, prompt, answer)",
        "_DATA: list[tuple[str, str, str]] = [",
    ]
    for r in rows:
        lines.append(
            f"    ({_py_literal(r['slug'])}, {_py_literal(r['prompt'])}, {_py_literal(r['answer'])}),"
        )
    lines += [
        "]",
        "",
        "prompts = [prompt for _slug, prompt, _answer in _DATA]",
        "seed_responses = [\"\"] * len(prompts)  # base model: no seed, trace the next token",
        "labels = [slug for slug, _prompt, _answer in _DATA]",
        "",
    ]
    path.write_text("\n".join(lines), encoding="utf-8")
    log.info("Wrote dataset module -> %s (%d prompts)", path, len(rows))


def main() -> None:
    ap = argparse.ArgumentParser(description="Fetch Neuronpedia graph prompts into a dataset module.")
    ap.add_argument("--model-id", default="google/gemma-2-2b", help="Model id (HF or bare).")
    ap.add_argument("--csv", type=Path, default=CSV_FILE, help="Graph list CSV.")
    ap.add_argument("--dataset-out", type=Path, default=DATASET_FILE, help="Dataset module to write.")
    ap.add_argument("--json-out", type=Path, default=REFERENCE_JSON, help="Reference JSON to write.")
    args = ap.parse_args()

    if not args.csv.exists():
        log.error("CSV not found: %s", args.csv)
        sys.exit(1)

    with open(args.csv, newline="", encoding="utf-8") as f:
        csv_rows = [row for row in csv.DictReader(f) if (row.get("slug") or "").strip()]
    log.info("Read %d graphs from %s", len(csv_rows), args.csv)

    rows: list[dict] = []
    reference: dict[str, dict] = {}
    for row in csv_rows:
        slug = row["slug"].strip()
        try:
            graph = fetch_graph(args.model_id, slug)
            prompt, tokens = extract_prompt(graph)
        except Exception as exc:  # noqa: BLE001
            log.error("  %s: %s — skipping", slug, exc)
            continue
        answer = answer_from_notes(row.get("notes", ""))
        rows.append({"slug": slug, "prompt": prompt, "answer": answer})
        reference[slug] = {
            "prompt": prompt,
            "answer": answer,
            "share_url": (row.get("share_url") or "").strip(),
            "prompt_tokens": tokens,
        }
        log.info("  %-28s %r  -> %r", slug, prompt, answer)

    if not rows:
        log.error("No prompts fetched — nothing written.")
        sys.exit(1)

    write_dataset_module(rows, args.dataset_out)
    args.json_out.write_text(json.dumps(reference, indent=2, ensure_ascii=False), encoding="utf-8")
    log.info("Wrote reference JSON -> %s", args.json_out)
    log.info("Done. %d/%d graphs fetched.", len(rows), len(csv_rows))


if __name__ == "__main__":
    main()
